version: "3.9"
services:
  mongo:
    image: "mongo:latest"
    container_name: "mongo"
    ports:
      - "27017:27017"
    networks:
      - "web.network"
    volumes:
      - mongodata:/data/db
      - mongodb_config:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
  redis:
    container_name: "redis"
    image: redis:alpine
    ports: 
      - "6379:6379"
    networks:
      - "web.network"
    volumes:
      - redis-data:/data
  web:
    build: .
    container_name: "0auth"
    ports:
      - "3000:3000"
    volumes:
      - ".:/app"
    restart: "always"
    environment:
      - Replica= {{.Task.Name}}
    depends_on:
      - mongo
      - redis
    networks:
      - "web.network"
    deploy:
      replicas: 1
networks:
  web.network:
volumes:
  mongodata:
  mongodb_config:
  redis-data:
    driver: local